events {}

http {
	server {
		listen 8500;
		ssl_protocols TLSv1.3;
		ssl_certificate /etc/nginx/ssl/nginx.crt;
		ssl_certificate_key /etc/nginx/ssl/nginx.key;

		error_log /var/log/nginx/debug.log debug;

		root /var/lib/nginx/html;
		index index.html index.php;
		server_name localhost;
		location / {
			try_files $uri $uri/ =404;
		}
		#location ~ \.php$ {
		#	include snippets/fastcgi-php.conf;
		#	fastcgi_pass wordpress:9000;
		#}
	}
}
