services:
  nginx:
    container_name: nginx
    build: requirements/nginx/.
    depends_on:
      - wordpress
    ports: 
      - 443:443
    networks:
      - docker_network
    volumes: 
      # - /home/${USERNAME}/data/WordPress:/var/www/html
      - wordpress_data:/var/www/html
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/.
    depends_on:
      - mariadb
    networks:
      - docker_network
    volumes: 
      # - /home/${USERNAME}/data/WordPress:/var/www/html
      - wordpress_data:/var/www/html
    environment:
      - DB=${DB}
      - DB_USER=${DB_USER}
      - DOMAIN=${DOMAIN}
      - WP_ADMIN=${WP_ADMIN}
      - WP_USER=${WP_USER}
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb/.
    networks:
      - docker_network
    volumes:
      # - /home/${USERNAME}/data/DB:/var/lib/mysql
      - mariadb_data:/var/lib/mysql
    environment:
      - DB=${DB}
      - DB_USER=${DB_USER}
    secrets:
      - db_root_password
      - db_password
    restart: always

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

networks:
  docker_network:

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/DB
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USERNAME}/data/WordPress